package com.cardinal.exception;

public class TestOwnException {

	public static void main(String[] args) {
		// TODO 自动生成的方法存根

	}

}
